# Generated by Django 5.0 on 2023-12-30 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='Sin categoría', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
